apiVersion: 1

datasources:
  - name: TeslaMate
    uid: TeslaMate
    type: grafana-postgresql-datasource
    access: proxy
    url: ${DATABASE_HOST:-database}:${DATABASE_PORT:-5432}
    user: ${DATABASE_USER:-teslamate}
    database: ${DATABASE_NAME:-teslamate}
    secureJsonData:
      password: ${DATABASE_PASS}
    jsonData:
      postgresVersion: 1500
      sslmode: disable
    isDefault: true
    editable: true
    version: 1
